/*
 This file contains SQL queries which will
 result in tables adhering to the project schema (https://dbdiagram.io/d/6032ba00fcdcb6230b20d17b)
 and populated with the sample csv files generated by the mmJC_parser program.
 Tested with MySQL 8.0.21 in DBeaver 7.3.5.
*/
 
-- 1) Dimension table: dim_variable -------------------------------------
CREATE TABLE `dim_variable` (
  `id` int NOT NULL,
  `var_name` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOAD DATA LOCAL INFILE '../mmJC_parser/data/processed/db/dim_variable.csv' 
INTO TABLE dim_variable FIELDS TERMINATED BY ','
ENCLOSED BY '"' IGNORE 1 LINES;

-- Add primary key and drop column 'id'
ALTER TABLE dim_variable ADD var_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (var_id),
DROP COLUMN id;


-- 2) Dimension table: dim_time -------------------------------------------
/*Due to issues in python code, there are duplicated rows in the input file.
To solve this problem here we create a temperary table to load data,
select the unique rows (i.e.,group by hours),
then create table dim_time
*/

CREATE TABLE `dim_time_raw` (
  `id` int NOT NULL,
  `hours` float NOT NULL,
  `probe` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOAD DATA LOCAL INFILE '../mmJC_parser/data/processed/db/dim_time.csv' 
INTO TABLE dim_time_raw FIELDS TERMINATED BY ','
ENCLOSED BY '"' IGNORE 1 LINES;

-- Create dim_time table after removing duplicated rows
CREATE TABLE dim_time
SELECT * FROM dim_time_raw 
GROUP BY hours;


-- Add primary key and drop column 'id'
ALTER TABLE dim_time ADD time_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (time_id),
DROP COLUMN id;

-- update probe to timestamp
UPDATE dim_time 
SET `probe` = STR_TO_DATE(`probe`, '%m/%d/%Y %h:%i:%s %p');  

ALTER TABLE dim_time modify column `probe` timestamp;



-- 3) Dimension table: dim_station ---------------------------------------
CREATE TABLE dim_station (
   `id` int NOT NULL,
   `station_name` varchar(32) NOT NULL,
   `treatment` varchar(32) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET =latin1;

LOAD DATA LOCAL INFILE '../mmJC_parser/data/processed/db/dim_stations.csv'   
INTO TABLE dim_station FIELDS TERMINATED BY ','
ENCLOSED BY '"' IGNORE 1 LINES;

ALTER TABLE dim_station 
ADD station_id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
ADD PRIMARY KEY (station_id),
DROP COLUMN id;

/* 
-----NOTE------
The CSV files 'fact_records.csv' and 'fact_LH.csv' are different from the schema design,
because columns for the foreign keys have not been created.

Here we import the two tables as-is, conduct joins with the dimension tables to reference data, 
then create new tables which adhere to the schema. 

*/
-- 4) Fact table: fact_records -------------------------------------------
-- Load in raw fact_records file into temp table `fact_records_raw` first
CREATE TABLE `fact_records_raw` (
    id int NOT NULL,
    station_name varchar(32) NOT NULL,
    hours float NOT NULL,
    var_name varchar(32) NOT NULL,
    record_value float NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

LOAD DATA LOCAL INFILE '../mmJC_parser/data/processed/db/fact_records.csv'   
INTO TABLE fact_records_raw FIELDS TERMINATED BY ','
ENCLOSED BY '"' IGNORE 1 LINES;

ALTER TABLE fact_records_raw
ADD record_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY(record_id),
DROP COLUMN id;


-- Create table 'fact_records'
CREATE TABLE fact_records 
SELECT a.record_id, c.station_id, b.time_id, d.var_id, a.record_value 
FROM fact_records_raw a
LEFT JOIN dim_time b 
ON a.hours = b.hours 
LEFT JOIN 
dim_station c 
ON a.station_name = c.station_name
LEFT JOIN 
dim_variable d 
ON a.var_name = d.var_name;


-- 5) Fact table: fact_LH -------------------------------------------------
-- Load in raw fact_LH file into temp table `fact_LH_raw` first
CREATE TABLE `fact_LH_raw` (
   id int NOT NULL,
   station_name varchar(32) NOT NULL,
   hours float NOT NULL,
   LH_record varchar(255) NOT NULL 
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

LOAD DATA LOCAL INFILE '../mmJC_parser/data/processed/db/fact_LH.csv'   
INTO TABLE fact_LH_raw FIELDS TERMINATED BY ','
ENCLOSED BY '"' IGNORE 1 LINES;

ALTER TABLE fact_LH_raw
ADD LH_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY(LH_id),
DROP COLUMN id;

-- perform joins and create fact_LH
CREATE TABLE fact_LH 

SELECT a.LH_id, c.station_id, b.time_id, a.LH_record
FROM fact_LH_raw a 
LEFT JOIN dim_time b 
ON a.hours = b.hours 
LEFT JOIN 
dim_station c 
ON a.station_name = c.station_name; 


-- Lastly, add foreign key constraints -------------------------------------------------
ALTER TABLE fact_LH
ADD FOREIGN KEY (station_id) REFERENCES dim_station(station_id)
ADD FOREIGN KEY (time_id) REFERENCES dim_time(time_id)

ALTER TABLE fact_records 
ADD FOREIGN KEY (station_id) REFERENCES dim_station(station_id),
ADD FOREIGN KEY (time_id) REFERENCES dim_time(time_id),
ADD FOREIGN KEY (var_id) REFERENCES dim_variable(var_id)


-- Clean up temporary tables 
DROP TABLE dim_time_raw ;
DROP TABLE fact_LH_raw ;
DROP TABLE fact_records_raw ;





